/** 首页路线与产品共用阶段映射；占位属于展示状态，不写入虚构产品。 */
export const careerJourney = [
  {
    id: "prepare",
    illustrationAlt: "黑白铅笔漫画：戴眼镜的求职者拿着简历和铅笔，认真打磨经历",
    name: "打磨简历",
    icon: "file",
    stages: ["prepare"],
    description: "让经历清晰，让你的价值被看见。",
    upcoming: "简历与作品集工具",
    note: "下一份好简历，从这里开始。",
  },
  {
    id: "practice",
    illustrationAlt: "黑白铅笔漫画：求职者翻阅编程书籍，在电脑前准备技术知识",
    name: "技术准备",
    icon: "code",
    stages: ["practice"],
    description: "从知识梳理，到可以讲清楚的解题思路。",
    upcoming: "技术备战工具",
    note: "算法、八股与系统设计，期待在这里相遇。",
  },
  {
    id: "mock",
    illustrationAlt: "黑白铅笔漫画：求职者戴着耳麦，对着电脑练习面试表达",
    name: "练习面试",
    icon: "mic",
    stages: ["mock"],
    description: "提前练习，把不确定变成从容。",
    upcoming: "面试练习工具",
    note: "下一次开口，让准备更充分。",
  },
  {
    id: "search",
    illustrationAlt: "黑白铅笔漫画：求职者用放大镜寻找适合自己的工作机会",
    name: "寻找机会",
    icon: "briefcase",
    stages: ["search", "apply"],
    description: "找到适合的岗位，让每次投递有方向。",
    upcoming: "机会探索工具",
    note: "岗位发现、内推与投递管理，敬请期待。",
  },
  {
    id: "offer",
    illustrationAlt: "黑白铅笔漫画：求职者拿着两份录用文件，认真比较不同选择",
    name: "选择 Offer",
    icon: "chart",
    stages: ["offer"],
    description: "看清每个选择，认真决定下一程。",
    upcoming: "Offer 决策工具",
    note: "薪资比较与机会评估，未来在这里见。",
  },
];
